# Generated by Django 4.2.5 on 2023-12-22 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_course_certificate_course_deadline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='language',
            old_name='language',
            new_name='name',
        ),
    ]
