# Generated by Django 4.2.5 on 2023-12-22 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_payment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Author',
            new_name='Instructor',
        ),
    ]
